fplll/fpylll

- src/fpylll/contrib/simple_bkz.py
This is just a very minor fix for an error that i get when trying to create a BKZReduction object.
> bug fix: constant ROW_EXPO not found

- setup.py
- src/fpylll/config.pyx
- src/fpylll/fplll/bkz.pyx
- src/fpylll/fplll/decl.pxd
- src/fpylll/fplll/enumeration.pyx
- src/fpylll/fplll/gso.pyx
- src/fpylll/fplll/lll.pyx
- src/fpylll/fplll/pruner.pyx
- src/fpylll/numpy.pyx
- src/fpylll/util.pyx
Currently long double is disabled explicitly on Cygwin where it is known not to be available (more specifically long double functions are just aliases for the normal double versions).
This does keep the `mpz_ld` member of the `fplll_type_t` enum, even without `HAVE_LONG_DOUBLE`, which was convenient in a few places, but this could be removed with a little restructuring.
I've confirmed all the tests pass for me with this patch.  Fixes #40
> Disable long double functionality where not available.

- src/fpylll/fplll/bkz.pyx
Description: source typo: controversial
Correct spelling error as reported by lintian in some binaries; meant to silence lintian.
Origin: vendor, Debian
Bug: https://github.com/fplll/fpylll/issues/43
Comment: spelling-error-in-binary
Author: Jerome Benoit <calculus@rezozer.net>
Last-Update: 2016-10-22
> correct spelling errors as detected by Lintian (controversial)

- src/fpylll/fplll/integer_matrix.pyx
Description: source typo: uncontroversial
Correct spelling error as reported by lintian in some binaries; meant to silence lintian.
Origin: vendor, Debian
Comment: spelling-error-in-binary
Author: Jerome Benoit <calculus@rezozer.net>
Last-Update: 2016-10-22
> correct spelling errors as detected by Lintian (uncontroversial)

- README.rst
remove 4 non-ascii characters, that broke the build with python3 in sage
> ascii only, for python3 compatibility

- setup.py
- src/fpylll/config.pyx
- src/fpylll/fplll/bkz.pyx
- src/fpylll/fplll/bkz_param.pyx
- src/fpylll/fplll/enumeration.pyx
- src/fpylll/fplll/gso.pyx
- src/fpylll/fplll/integer_matrix.pyx
- src/fpylll/fplll/lll.pyx
- src/fpylll/fplll/pruner.pyx
- src/fpylll/fplll/svpcvp.pyx
- src/fpylll/fplll/wrapper.pyx
- src/fpylll/io.pyx
- src/fpylll/numpy.pyx
- src/fpylll/util.pyx
In recent versions of cysignals, the `.pxi` files are deprecated. Instead, regular `cimports` should be used. This avoids the need for https://github.com/cython/cython/pull/483 and goes along with the Cython philosophy that one should prefer `cimport` over `include`.
> cimport cysignals instead of using includes

- setup.py
Instead of adding the `include` and `lib` directories only when `VIRTUAL_ENV` is set, unconditionally set those directories. This is needed for other "virtual envs" such as Conda.
> Unconditionally add include and lib directories

- src/fpylll/fplll/integer_matrix.pyx
Fix bug on converting IntegerMatrix to sage matrix like object which only supports m[i][j] assignment operation.
> bugfix for IntegerMatrix.to_matrix for A[i][j]

- src/fpylll/io.pyx
On Debian, running `python -c 'import sage.all'` fails with:
~~~~
[..]
File "/usr/lib/python2.7/dist-packages/sage/interfaces/maxima.py", line 539, in __init__
raise RuntimeError('You must get the file local/bin/sage-maxima.lisp')
RuntimeError: You must get the file local/bin/sage-maxima.lisp
~~~~
The underlying reason being that `sage-env` logic is not run, so `SAGE_LOCAL` et.al. are not defined. This causes `python -c "import fpylll"` to fail with the same error, when `sagemath` is installed.
This commit fixes this, by making `fpylll` more robust to these sorts of errors - it will fall back to the `have_sage = False` behaviour when the import fails but for a reason other than `ImportError`.
(OTOH, if `python -c 'import sage.all'` is *supposed* to work, then this is also a bug in Sage - …
> Be more robust to different types of errors when importing Sage

- src/fpylll/algorithms/bkz.py
- src/fpylll/algorithms/bkz2.py
- src/fpylll/algorithms/pbkz.py
- src/fpylll/algorithms/simple_bkz.py
- src/fpylll/algorithms/simple_dbkz.py
- src/fpylll/fplll/enumeration.pyx
- src/fpylll/fplll/gso.pyx
- tests/test_cvp.py
- tests/test_multisol_enum.py
- add sub-solution support
- make API consistent between sub-solutions and full solutions/fplll
> enable sub-solutions

- docs/conf.py
- suggestions.txt
Instead of relying on a custom patched Sphinx, use a released version of Sphinx.
> Use official version of Sphinx

- src/fpylll/fplll/decl.pxd
- src/fpylll/fplll/enumeration.pyx
- src/fpylll/fplll/gso.pyx
- src/fpylll/fplll/lll.pyx
- src/fpylll/fplll/pruner.pyx
I feel like there's got to be a way to more cleanly manage imports for optionally defined types as in the `HAVE_LONG_DOUBLE` and `HAVE_QD` cases.  I'll have to think about that more in the meantime.
> Fix some broken declarations and imports when not HAVE_LONG_DOUBLE

- setup.py
This moves several of the operations that were performed at module-level in the `setup.py` into a subclass of the distutils `build_ext` command.  This way, operations that are only relevant to building extension modules are only performed when actually building extension modules, rather than unconditionally.
This allows certain operations like `./setup.py --name` and `./setup.py --version` to work without unnecessary side-effects.
One possible small regression this introduces is that if you want the Cython-generated C sources to be included in a source distribution it's now necessary to run `./setup.py build_ext sdist`, rather than `./setup.py sdist`, though we could also make it so that `build_ext` is run automatically as a prerequisite of `sdist`.  That said, I'm not sure if this is …
> Refactor setup.py a bit

- src/fpylll/fplll/bkz_param.pyx
Description: source typo
Correct spelling errors as reported by lintian in the binary library; meant
to silence lintian and eventually to be submitted to the upstream maintainer.
Origin: vendor, Debian
Comment: spelling-error-in-binary
Author: Jerome Benoit <calculus@rezozer.net>
Last-Update: 2018-01-26
> correct spelling errors as detected by Lintian

- .travis.yml
- setup.py
Building off of #106, this adds four new configurations that are built and tested on Travis (in this case all using Python 2.7 for now): `HAVE_LONG_DOUBLE=False`, `HAVE_QD=False`, `HAVE_NUMPY=False`, and `HAVE_LONG_DOUBLE = HAVE_QD = False`.
This should cover most branches in the Cython code impacted by these compile-time variables, if not all.
As you'll see, Travis finds a few test failures in these cases.
> Add additional configurations to Travis build

- setup.py
Otherwise python3 will use the default system encoding. That will fail if that happens to be ascii. `io.open` instead of regular `open` is needed for python2 backwards compatibility[1].
[1] https://stackoverflow.com/questions/10971033/backporting-python-3-openencoding-utf-8-to-python-2
> Specify README file encoding

- src/fpylll/algorithms/bkz.py
- src/fpylll/tools/bkz_stats.py
Allows for GS lengths to be saved in tracer for later inspection. dump_gso_filename still allows for the GSO to be dumped to a file outside of the tracer.
> dump squared GSO lengths to tracer object at the end of each tour

- README.rst
Not sure how common of an issue this is, but personally I'd love to see a note on this somewhere. 
Probably, it could also be merged with the manual install instructions by adding some python2 vs python3 notes and adding an `export VIRTUAL_ENV=$SAGE_LOCAL` command.
> Instructions for upgrading inside of Sage

- README.rst
Apologies for the double PR, just noticed a typo (`python` vs `python3`). Took the occasion to add a comment clarifying the last step.
> python -> python3 + comment

- src/fpylll/fplll/svpcvp.pyx
- src/fpylll/io.pyx
- tests/test_svp.py
- `SVP.shortest_vector` now mostly does the right thing, i.e. it is no longer the wrong thing to call
- both bomb out with a helpful error message when the dimensions are too large.
> SVP & CVP Improvements

- src/fpylll/algorithms/bkz.py
- src/fpylll/tools/bkz_stats.py
When running big BKZ instances, recursive calls make BKZ trace *huge*, For example, 40 instances in parallel, I manage to choke a server that had 1.5TB of RAM... And I didn't even needed the trace in the first place, but there is no way around it in the current API.
The proposed patches:
- adds a tracing parameter on __call__ to fpylll.algorithm.bkz
- defaults it to False.
> Tracing = Memory leak

- src/fpylll/gmp/pylong.pxd
https://docs.python.org/3.11/whatsnew/3.11.html
https://github.com/python/cpython/issues/79315
Fixes #230
> Do not include "longintrepr.h"

- src/fpylll/fplll/bkz_param.pyx
The handling for SAGE_LOCAL changed but this test remained.
Should fix #233
> Remove redundant doctest.

- bootstrap.sh
Hi, 
I noticed when testing the bootstrap script and custom changes in fplll that errors during the compilation of fplll are ignored by the script.
This is due to an error in the spacing, the same as the one fixed some time ago in g6k, see https://github.com/fplll/g6k/pull/86.
> Fix error ignored during fplll compilation

- README.rst
FWIW: I also think that fpylll dropped support for Python 2 a while ago (and tests definitely don't use it) but I'm not sure. Feel free to remove that bit if it's not strictly true.
> Update README to remove Travis.

- src/fpylll/gmp/pycore_long.h
- src/fpylll/gmp/pycore_long.pxd
- src/fpylll/gmp/pylong.pxd
- src/fpylll/gmp/pylong.pyx
The necessary functions are copied from cpython 3.12 `Include/internal/pycore_long.h`, which is private. This should make it easy to copy new versions if cpython internals change. For cpython < 3.12 I implemented equivalent functions.
All of this is placed in separate files `pycore_long.pxd` and `pycore_long.h` copied from https://github.com/sagemath/cypari2/issues/137.
Tested in 64-bit and 32-bit x86.
Fixes: #246
> Support python 3.12

- pyproject.toml
- setup.py
... and remove Cython from the runtime dependencies (`install_requires`); it is only needed at build time.
> Declare build deps in pyproject.toml

- src/fpylll/gmp/pycore_long.h
Related to #262 
Locally, after fixing this typo, I'm able to manually install the package. 
We need to cut another minor version release to PyPI and try to `pip wheel` on the new release to see if the installation error goes away (in which case we can close the linked issue)
Either way, this appears to be a clear typo that should be fixed.
> fix: typo in gmp/pycore_long 

- src/fpylll/fplll/bkz.pyx
I noticed fpylll did not support for returning transformation matrix on bkz_reduction.
fplll supports the interface, so I wrote a simple interface on fpylll.
> add transformation interface to bkz_reduction

- setup.py
Fixes #269.
This problem doesn't affect `x86_64-darwin`, hence why `platform` is pulled in to specifically check if we're on ARM.
> disable long double on aarch64-darwin

- src/fpylll/algorithms/babai.py
This PR contains one fix and one improvement.
- The fixed issue is that in `fpylll.algorithms.babai`, when the norm of the largest vector is calculated, `ceil(A[-2].norm())`  is used which casts the value to a double after which it is rounded. This is prone to large imprecision issues and when sufficiently large integers are used it may lead to issues with infinity. We instead opt for calculating the norm in Python and using `math.isqrt` which is precise.
- Extra arguments and keyword arguments passed to `babai` will now also be passed onto `LLL.reduction`, which could be useful in some cases.
> Fixes in fpylll.algorithms.babai

- .github/workflows/release.yml
Also removes the use of the defunct actions/create-release.
- Resolves #205.
> Build binary wheels for PyPI with cibuildwheel

- src/fpylll/algorithms/babai.py
- src/fpylll/fplll/svpcvp.pyx
- src/fpylll/tools/bkz_simulator.py
By modifying the Chen--Nguyen'11 simulator to not compute the sum in each iteration, but instead keep track of the volume of a block of the basis, this code is shorter (I hope more readable) and ~8x faster. Moreover, add a `log_simulator` method, which works on the `log2(sqrt(squared GS))` norms, which is used in the lattice-estimator (see discussion in https://github.com/malb/lattice-estimator/issues/128 ).
The documentation suggests that the code yields the exact same answers.
Also, normalized "EXAMPLE::" as there were some files having a space, and `bkz_simulator.py` had a single colon so the code may not have been checked in CI (an import was missing for average_simulator_prob).
> Refactor BKZ 2.0 simulator

- pyproject.toml
`cysignals` version 1.12.0 appears to be broken when building this package (see issue #278). This forces builds that consume `pyproject.toml` (e.g. poetry based builds) to use a `cysignals` version that is not broken.
I have verified this fixes poetry builds and installs locally, happy to also run any other tests or validation needed.
> Issue #278: Reference functional cysignals version

- .github/workflows/pypi-publish.yml
This new workflow can be invoked manually. It downloads the distributions built by a run of `release.yml` and uploads them to PyPI. @malb
> .github/workflows/pypi-publish.yml: New

- bootstrap.sh
- docs/conf.py
- pyproject.toml
- requirements.txt
- setup.py
- only append once all code to fpylll-env/bin/activate so deactivating is not necessary
- pick up on return code of `make clean` in FPLLL, like G6K does.
- fix DeprecationWarning in setup.py and docs/conf.py for getting `__version__`
- depend on most recent cysignals (1.12.2) again as this one works again.
- change return values of bootstrap.sh to make all errors have different ones
Note: $retval was not updated after `make install` previously.
Closes: #278
> Update bootstrap.sh & setup.py

- src/fpylll/algorithms/babai.py
> CVP.babai: search for correct row instead of assuming it's -1

- Dockerfile
- README.rst
- docs/example-gauss-circle-problem.rst
- docs/example-linear-diophantine-equations.rst
- docs/index.rst
- src/fpylll/io.pyx
This may be related to https://github.com/fplll/fpylll/pull/293
It appears I/O was trying to cast values to python integers using `long(value)`, but that is no longer supported (use `int(value)`) in Python 3.x (see https://peps.python.org/pep-0237/ ).
I'm not sure how this seemed to work before, perhaps because there was a try/catch around it in `assign_Z_NR_mpz`?
> long is not longer supported in Python

- pyproject.toml
See https://github.com/passagemath/passagemath/pull/651 - fpylll cannot be built with Cython 3.1.0b0.
I suggest to release an fpylll version with an upper version bound on Cython before Cython 3.1 is released.
> pyproject.toml: Require Cython < 3.1
