- src/fpylll/gso.pyx
forgot to add this to the previous pull request. it's required for dbkz reduction. sorry about that.
> add negation of row to gso

- src/fpylll/bkz.pyx
Not sure if you like this but I find that this code is more readable.
> Clarified if statement

- src/fpylll/__init__.py
- src/fpylll/algorithms/bkz.py
- src/fpylll/algorithms/bkz2.py
- src/fpylll/fplll/gso.pyx
- src/fpylll/fplll/lll.pyx
- src/fpylll/fplll/svpcvp.pyx
- tests/test_bkz_python.py
fixes #28 (performance to be investigated)
> BKZ2 in Python

- src/fpylll/__init__.py
- src/fpylll/fplll/svpcvp.pyx
As CVP is not longer experimental in fplll, we can start to use it from fpylll.
> API for CVP calls

- setup.py
> get SAGE_SRC from sage/env.py rather than the environment

- install-dependencies.sh
If there is a branch on fplll with the same name as the current fpylll branch, then travis-ci will build & test against that.
> Attempt build against matching name fplll branch

- src/fpylll/fplll/pruner.pyx
- tests/test_multisol_enum.py
- tests/test_pruner.py
- tests/test_util.py
Sorry for to API def war... But I think this makes more sense.
> change interface to prune, and added more tests

- src/fpylll/fplll/decl.pxd
- src/fpylll/fplll/pruner.pyx
- tests/test_util.py
Should be fairly self-explanatory; thanks in advance?
> More miscellaneous fixes for non-long double support

- .travis.yml
See https://github.com/sagemath/cysignals/commit/a1dd07e7a34bc9469cb6d53c354ac84a21ae2a18
> No need to install Cython as separate step

- readthedocs-conda.yml
- readthedocs.yml
- setup.py
- suggestions.txt
http://fpylll.readthedocs.io/en/latest/
> Support ReadTheDocs

- src/fpylll/fplll/enumeration.pyx
Added info about multiple solutions
> enumeration doc fix

- src/fpylll/algorithms/bkz2.py
> Bkz2 get pruning

- src/fpylll/__init__.py
- src/fpylll/fplll/enumeration.pyx
- src/fpylll/fplll/fplll.pxd
- src/fpylll/fplll/gso.pyx
- src/fpylll/fplll/integer_matrix.pyx
- src/fpylll/fplll/pruner.pyx
- src/fpylll/fplll/sieve_gauss.pyx
- src/fpylll/fplll/svpcvp.pyx
- src/fpylll/tools/quality.py
- src/fpylll/util.pyx
- src/fpylll/util_helper.h
- tests/test_bkz_python.py
- tests/test_precision.py
- tests/test_random.py
- tests/test_simple_bkz.py
```python
from fpylll import *
import ctypes
enumlib = ctypes.cdll.LoadLibrary("enumlib.so")
enumlib._Z20enumlib_set_logleveli(2)
fn = enumlib._Z17enumlib_enumerateidSt8functionIFvPdmbS0_S0_EES_IFddS0_EES_IFvdS0_iEEbb
FPLLL.set_external_enumerator(fn)
A = IntegerMatrix.random(100, "qary", k=50, bits=30)
BKZ.reduction(A, o=BKZ.Param(block_size=50, strategies=BKZ.DEFAULT_STRATEGY, max_loops=1, flags=BKZ.VERBOSE|BKZ.MAX_LOOPS))
```
> Support for external enumeration libraries using ctypes

- src/fpylll/algorithms/bkz.py
- src/fpylll/tools/bkz_stats.py
- src/fpylll/tools/compare.py
I suggest to merge the comparison "framework" before it bitrots.
> Compare BKZ variants

- src/fpylll/algorithms/bkz2.py
- src/fpylll/util.pyx
> Use FPLLL's RNG

- src/fpylll/fplll/fplll.pxd
- src/fpylll/fplll/svpcvp.pyx
Adds support for specifying the CVP method, also update the fplll interface. Fixes #136 .
> Add CVP method support.

- src/fpylll/fplll/pruner.pyx
> Fix prune target condition, when using number of solutions metric.

- src/fpylll/algorithms/bkz2.py
> use r_exp() in BKZ2

- src/fpylll/config.pyx
- src/fpylll/fplll/enumeration.pyx
- src/fpylll/fplll/fplll.pxd
> Enumeration cost per level

- src/fpylll/algorithms/bkz.py
This is a trivial PR: it just fixes the most recent open issue about the svp_postprocessing docstring.
> Update docstring for #183

- setup.py
> add install_requires

- bootstrap.sh
> import Marc's g6k bootstrap.sh fixes

- .github/workflows/sdist.yml
Test for issues such as that reported in #199
> test python setup.py sdist

- src/fpylll/fplll/bkz.pyx
- src/fpylll/fplll/gso.pyx
- src/fpylll/fplll/lll.pyx
Figured that since I'd opened a new issue I'd fix an old one so it balanced out.
This just fixes some of the docstrings that were incorrect as originally mentioned in #213 by @fvirdia.
> Fix for #213 (Outdated docstrings)

- src/fpylll/fplll/bkz_param.pyx
- src/fpylll/fplll/fplll.pxd
This fixes #218 by doing as #218 suggests. 
Not sure if this is the best approach to do this: it essentially just catches the C++ exception and then try again with the newer path. 
Happy to take pointers on how to make it better.
> Fix sage path

- src/fpylll/algorithms/babai.py
- src/fpylll/algorithms/bkz2.py
- src/fpylll/fplll/decl.pxd
- src/fpylll/fplll/fplll.pxd
- src/fpylll/fplll/gso.pyx
- src/fpylll/fplll/svpcvp.pyx
- src/fpylll/io.pxd
- src/fpylll/io.pyx
- src/fpylll/util.pyx
- tests/test_callback_enum.py
- tests/test_gso.py
> Call out to the new full-precision Babai

- src/fpylll/fplll/integer_matrix.pyx
- src/fpylll/io.pyx
- src/fpylll/numpy.pyx
- tests/test_numpy.py
> Add support for converting (integer) numpy arrays to IntegerMatrix.

- .github/workflows/release.yml
- using https://github.com/passagemath/passagemath/pull/444 
Preview at https://github.com/mkoeppe/fpylll/actions/runs/12192006362 @malb
> release.yml: Build wheels using fplll 5.5.0

- .github/workflows/release.yml
- Restores functionality lost to bitrot and removal in #276.
- Fixes #282 @malb 
Preview: https://github.com/mkoeppe/fpylll/actions/runs/12207696340/job/34060585621 => https://github.com/mkoeppe/fpylll/releases/tag/0.6.2-test
> release.yml: Create GH release using softprops/action-gh-release

- .github/workflows/pypi-publish.yml
> .github/workflows/pypi-publish.yml: Fix up

- pyproject.toml
- src/fpylll/io.pyx
> pyproject.toml (build-system requires): Add numpy
